package com.lesofn.archforge.server.admin.metatable;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

import com.lesofn.archforge.common.persistence.testsupport.AbstractIntegrationTest;
import com.lesofn.archforge.meta.table.api.domain.MetaColumn;
import com.lesofn.archforge.meta.table.api.dto.ImportableTableInfo;
import com.lesofn.archforge.meta.table.api.dto.MetaDataQuery;
import com.lesofn.archforge.meta.table.api.dto.MetaPageResponse;
import com.lesofn.archforge.meta.table.api.dto.TableImportPreview;
import com.lesofn.archforge.meta.table.api.errors.MetaTableException;
import com.lesofn.archforge.meta.table.api.service.MetaTableAdminService;
import com.lesofn.archforge.meta.table.api.service.MetaTableCrudService;
import com.lesofn.archforge.meta.table.api.service.MetaTableImportService;
import com.lesofn.archforge.server.admin.Application;
import java.util.List;
import java.util.Map;
import org.jspecify.annotations.Nullable;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestInstance;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;

/**
 * End-to-end tests for adopting existing physical tables into meta-table:
 * real PostgreSQL schema introspection, compatibility grading, registration and
 * post-import CRUD against the untouched physical table.
 */
@SpringBootTest(classes = Application.class, webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
@Tag("slow")
class MetaTableImportIntegrationTest extends AbstractIntegrationTest {

    @Autowired
    private MetaTableImportService importService;

    @Autowired
    private MetaTableAdminService adminService;

    @Autowired
    private MetaTableCrudService crudService;

    @Autowired
    @Qualifier("metaTableJdbcTemplate")
    private NamedParameterJdbcTemplate jdbcTemplate;

    private void exec(String sql) {
        jdbcTemplate.getJdbcOperations().execute(sql);
    }

    @Test
    void compatibleTableImportThenCrudWorks() {
        exec("""
                CREATE TABLE legacy_goods (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    creator_id BIGINT, create_time TIMESTAMP,
                    updater_id BIGINT, update_time TIMESTAMP,
                    deleted INT DEFAULT 0 NOT NULL,
                    goods_name VARCHAR(64) NOT NULL,
                    price NUMERIC(10,2),
                    stock BIGINT DEFAULT 0
                )
                """);

        ImportableTableInfo info = findTable("legacy_goods");
        assertNotNull(info);
        assertTrue(info.isCompatible(), String.join(";", info.getReasons()));

        TableImportPreview preview = importService.preview("legacy_goods");
        assertTrue(preview.isCompatible());
        assertEquals(9, preview.getColumns().size());

        Long tableId = importService.importTable("legacy_goods", "历史商品", null, 1L);
        try {
            List<MetaColumn> columns = adminService.findColumns(tableId);
            assertEquals(3, columns.size());
            assertEquals("goods_name", columns.get(0).getColumnCode());
            assertTrue(columns.get(0).getRequired());

            Long rowId = crudService.insert(tableId, Map.of("goods_name", "apple", "price", "3.5"), 7L);
            assertNotNull(rowId);

            MetaPageResponse<Map<String, Object>> page = crudService.list(tableId, MetaDataQuery.of(Map.of(), 1, 10));
            assertEquals(1, page.getTotal());
            assertEquals("apple", page.getList().get(0).get("goods_name"));
            assertEquals(0,
                    ((Number) java.util.Objects.requireNonNull(page.getList().get(0).get("stock"))).intValue());

            assertTrue(crudService.update(tableId, rowId, Map.of("goods_name", "pear"), 7L));
            assertTrue(crudService.softDelete(tableId, rowId, 7L));
            assertEquals(0, crudService.list(tableId, MetaDataQuery.of(Map.of(), 1, 10)).getTotal());
        } finally {
            adminService.delete(tableId, true);
        }
    }

    @Test
    void existingDataVisibleAfterImport() {
        exec("""
                CREATE TABLE legacy_stock (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    creator_id BIGINT, create_time TIMESTAMP,
                    updater_id BIGINT, update_time TIMESTAMP,
                    deleted INT DEFAULT 0 NOT NULL,
                    sku VARCHAR(32)
                )
                """);
        exec("INSERT INTO legacy_stock (sku) VALUES ('A1'), ('A2')");

        Long tableId = importService.importTable("legacy_stock", null, null, 1L);
        try {
            MetaPageResponse<Map<String, Object>> page = crudService.list(tableId, MetaDataQuery.of(Map.of(), 1, 10));
            assertEquals(2, page.getTotal());
        } finally {
            adminService.delete(tableId, true);
        }
    }

    @Test
    void incompatibleTableFlaggedAndImportRejected() {
        exec("""
                CREATE TABLE legacy_broken (
                    id BIGINT PRIMARY KEY,
                    name VARCHAR(32)
                )
                """);

        ImportableTableInfo info = findTable("legacy_broken");
        assertNotNull(info);
        assertFalse(info.isCompatible());
        assertTrue(info.getReasons().stream().anyMatch(r -> r.contains("deleted")), info.getReasons().toString());

        assertThrows(MetaTableException.class,
                () -> importService.importTable("legacy_broken", null, null, 1L));

        exec("DROP TABLE legacy_broken");
    }

    @Test
    void previewMapsIndexesAndComments() {
        exec("""
                CREATE TABLE legacy_book (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    creator_id BIGINT, create_time TIMESTAMP,
                    updater_id BIGINT, update_time TIMESTAMP,
                    deleted INT DEFAULT 0 NOT NULL,
                    isbn VARCHAR(20) NOT NULL,
                    title TEXT,
                    tags VARCHAR(64)[]
                )
                """);
        exec("CREATE UNIQUE INDEX uq_legacy_book_isbn ON legacy_book (isbn)");
        exec("CREATE INDEX idx_legacy_book_title_isbn ON legacy_book (title, isbn)");
        exec("COMMENT ON COLUMN legacy_book.isbn IS '书号'");

        try {
            TableImportPreview preview = importService.preview("legacy_book");
            assertTrue(preview.isCompatible(), String.join(";", preview.getReasons()));
            assertEquals(List.of("idx_legacy_book_title_isbn"), preview.getCompositeIndexes());

            TableImportPreview.PreviewColumn isbn = preview.getColumns().stream()
                    .filter(c -> "isbn".equals(c.getColumnCode())).findFirst().orElseThrow();
            assertEquals("STRING", isbn.getDataType());
            assertTrue(isbn.isUnique());
            assertTrue(isbn.isRequired());
            assertEquals("书号", isbn.getComment());

            TableImportPreview.PreviewColumn tags = preview.getColumns().stream()
                    .filter(c -> "tags".equals(c.getColumnCode())).findFirst().orElseThrow();
            assertEquals("ARRAY", tags.getDataType());
        } finally {
            exec("DROP TABLE legacy_book");
        }
    }

    @Test
    void sysPrefixedTableNotImportable() {
        // sys_user exists in the test schema but uses user_id PK — both name and PK incompatible
        ImportableTableInfo info = findTable("sys_user");
        assertNotNull(info);
        assertFalse(info.isCompatible());
    }

    private @Nullable ImportableTableInfo findTable(String name) {
        return importService.listImportable().stream()
                .filter(t -> t.getTableName().equals(name))
                .findFirst()
                .orElse(null);
    }
}
