package com.lesofn.archforge.meta.table.internal.ddl;

import com.lesofn.archforge.meta.table.api.domain.MetaColumn;
import com.lesofn.archforge.meta.table.api.domain.MetaTable;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.stream.Collectors;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Component;

/**
 * 元表格 DDL 生成器。
 */
@Component
@RequiredArgsConstructor
public class MetaTableDdlGenerator {

    private static final int PG_MAX_IDENTIFIER_LENGTH = 63;

    private final ColumnTypeResolver columnTypeResolver;

    /** 生成物理表名。 */
    public String physicalTableName(MetaTable table) {
        String prefix = table.getTablePrefix() == null ? "meta_" : table.getTablePrefix();
        return prefix + table.getTableCode();
    }

    /** 生成创建物理表的 SQL 与索引 SQL。 */
    public DdlResult generateCreateTable(MetaTable table, List<MetaColumn> columns) {
        SqlIdentifier.validateTableCode(table.getTableCode());
        String physicalName = SqlIdentifier.quote(physicalTableName(table));

        StringBuilder createSql = new StringBuilder();
        createSql.append("CREATE TABLE IF NOT EXISTS ").append(physicalName).append(" (\n");
        createSql.append("    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n");
        createSql.append("    creator_id BIGINT,\n");
        createSql.append("    create_time TIMESTAMP,\n");
        createSql.append("    updater_id BIGINT,\n");
        createSql.append("    update_time TIMESTAMP,\n");
        createSql.append("    deleted INT DEFAULT 0 NOT NULL");

        for (MetaColumn column : columns) {
            SqlIdentifier.validateColumnCode(column.getColumnCode());
            String columnDef = buildColumnDefinition(column);
            createSql.append(",\n    ").append(columnDef);
        }

        createSql.append("\n)");
        return new DdlResult(createSql.toString(), buildIndexStatements(table, columns));
    }

    /** 生成删除物理表 SQL。 */
    public String generateDropTable(String physicalTableName) {
        return "DROP TABLE IF EXISTS " + SqlIdentifier.quote(physicalTableName) + " CASCADE";
    }

    private String buildColumnDefinition(MetaColumn column) {
        String name = SqlIdentifier.quote(column.getColumnCode());
        String type = columnTypeResolver.resolve(column);
        StringBuilder sb = new StringBuilder();
        sb.append(name).append(' ').append(type);
        if (Boolean.TRUE.equals(column.getRequired())) {
            sb.append(" NOT NULL");
        }
        if (column.getDefaultValue() != null && !column.getDefaultValue().isEmpty()) {
            sb.append(" DEFAULT ").append(columnTypeResolver.formatDefaultValue(column));
        }
        return sb.toString();
    }

    private List<String> buildIndexStatements(MetaTable table, List<MetaColumn> columns) {
        List<String> statements = new ArrayList<>();
        String physicalTableCode = physicalTableName(table);

        // 复合索引：按 indexGroup 分组
        Map<String, List<MetaColumn>> grouped = columns.stream()
                .filter(c -> c.getIndexGroup() != null && !c.getIndexGroup().isEmpty())
                .filter(this::isIndexEnabled)
                .collect(Collectors.groupingBy(MetaColumn::getIndexGroup, LinkedHashMap::new, Collectors.toList()));

        for (Map.Entry<String, List<MetaColumn>> entry : grouped.entrySet()) {
            List<MetaColumn> groupColumns = entry.getValue().stream()
                    .sorted(Comparator.comparingInt(c -> c.getSort() == null ? 0 : c.getSort()))
                    .toList();
            boolean unique = groupColumns.stream().anyMatch(c -> Boolean.TRUE.equals(c.getUnique()));
            String indexType = groupColumns.get(0).getIndexType();
            if (indexType == null || indexType.isEmpty()) {
                indexType = "BTREE";
            }
            statements.add(buildCreateIndex(physicalTableCode, entry.getKey(), groupColumns, indexType, unique));
        }

        // 单列索引
        for (MetaColumn column : columns) {
            if (column.getIndexGroup() != null && !column.getIndexGroup().isEmpty()) {
                continue;
            }
            if (!isIndexEnabled(column)) {
                continue;
            }
            boolean unique = Boolean.TRUE.equals(column.getUnique());
            String indexType = column.getIndexType();
            if (indexType == null || indexType.isEmpty()) {
                indexType = "BTREE";
            }
            statements.add(buildCreateIndex(physicalTableCode, column.getColumnCode(), List.of(column), indexType, unique));
        }

        return statements;
    }

    private boolean isIndexEnabled(MetaColumn column) {
        return Boolean.TRUE.equals(column.getUnique()) || Boolean.TRUE.equals(column.getIndex());
    }

    private String buildCreateIndex(String physicalTableCode, String indexKey, List<MetaColumn> columns, String indexType,
            boolean unique) {
        String physicalName = SqlIdentifier.quote(physicalTableCode);
        String rawName = (unique ? "uq_" : "idx_") + physicalTableCode + "_" + indexKey;
        String indexName = rawName.length() > PG_MAX_IDENTIFIER_LENGTH ? rawName.substring(0, PG_MAX_IDENTIFIER_LENGTH)
                : rawName;

        List<String> indexedExpressions = columns.stream()
                .map(c -> indexExpression(c, indexType))
                .filter(Objects::nonNull)
                .toList();
        if (indexedExpressions.isEmpty()) {
            return "";
        }

        String columnsPart = String.join(", ", indexedExpressions);
        StringBuilder sb = new StringBuilder();
        sb.append("CREATE ");
        if (unique) {
            sb.append("UNIQUE ");
        }
        sb.append("INDEX IF NOT EXISTS ").append(SqlIdentifier.quote(indexName))
                .append(" ON ").append(physicalName);
        if ("GIN".equalsIgnoreCase(indexType) || "GIST".equalsIgnoreCase(indexType) || "FULLTEXT".equalsIgnoreCase(indexType)) {
            String pgType = "FULLTEXT".equalsIgnoreCase(indexType) ? "GIN" : indexType.toUpperCase();
            sb.append(" USING ").append(pgType);
        }
        sb.append(" (").append(columnsPart).append(")");
        if (unique) {
            sb.append(" WHERE deleted = 0");
        }
        return sb.toString();
    }

    private String indexExpression(MetaColumn column, String indexType) {
        String quoted = SqlIdentifier.quote(column.getColumnCode());
        if ("FULLTEXT".equalsIgnoreCase(indexType)) {
            return "to_tsvector('chinese', " + quoted + ")";
        }
        return quoted;
    }

    /** DDL 生成结果：建表语句 + 索引语句列表。 */
    public record DdlResult(String createTableSql, List<String> indexSqls) {
    }
}
