-- ${tableName}（${tableCode}）建表迁移：由 codegen 生成，审查后入库
-- 模块感知 Flyway：版本号在本目录 db/migration/${moduleSlug}/ 内自增
CREATE TABLE IF NOT EXISTS "${physicalTableName}" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    creator_id BIGINT,
    create_time TIMESTAMP,
    updater_id BIGINT,
    update_time TIMESTAMP,
    deleted INT DEFAULT 0 NOT NULL<#list columns as col>,
    "${col.columnCode}" ${col.sqlType}<#if !col.nullable> NOT NULL</#if><#if col.hasSqlDefault> DEFAULT ${col.sqlDefault}</#if><#if col.unique> UNIQUE</#if></#list>
);

CREATE INDEX IF NOT EXISTS "idx_${physicalTableName}_deleted" ON "${physicalTableName}" (deleted);
<#list columns as col>
<#if col.indexed && !col.unique>
CREATE INDEX IF NOT EXISTS "idx_${physicalTableName}_${col.columnCode}" ON "${physicalTableName}" ("${col.columnCode}");
</#if>
</#list>
