-- V15: 字典配置表 + 元表格字段 dict_code + 枚举选项迁移 + 菜单

CREATE TABLE IF NOT EXISTS sys_dict_type
(
    dict_type_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dict_code     VARCHAR(64)  NOT NULL UNIQUE,
    dict_name     VARCHAR(128) NOT NULL,
    description   VARCHAR(255),
    status        INT DEFAULT 1,
    sort          INT DEFAULT 0,
    creator_id    BIGINT,
    create_time   TIMESTAMP,
    updater_id    BIGINT,
    update_time   TIMESTAMP,
    deleted       INT DEFAULT 0 NOT NULL
);

CREATE TABLE IF NOT EXISTS sys_dict_item
(
    dict_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dict_type_id BIGINT       NOT NULL REFERENCES sys_dict_type (dict_type_id),
    item_code    VARCHAR(64)  NOT NULL,
    item_label   VARCHAR(128) NOT NULL,
    sort         INT DEFAULT 0,
    status       INT DEFAULT 1,
    creator_id   BIGINT,
    create_time  TIMESTAMP,
    updater_id   BIGINT,
    update_time  TIMESTAMP,
    deleted      INT DEFAULT 0 NOT NULL,
    UNIQUE (dict_type_id, item_code)
);

ALTER TABLE sys_meta_table_column
    ADD COLUMN IF NOT EXISTS dict_code VARCHAR(64);

-- 将历史 ENUM 字段的内联 options 迁移为字典配置
DO $$
DECLARE
    r       RECORD;
    dict_id BIGINT;
    e       JSONB;
    code    VARCHAR(64);
BEGIN
    FOR r IN
        SELECT c.id        AS column_id,
               c.column_code,
               c.column_name,
               c.options,
               t.table_code
        FROM sys_meta_table_column c
                 JOIN sys_meta_table t ON c.table_id = t.id
        WHERE c.data_type = 'ENUM'
          AND c.options IS NOT NULL
          AND c.options <> ''
          AND c.dict_code IS NULL
        LOOP
            code := substr('meta_' || r.table_code || '_' || r.column_code, 1, 64);

            INSERT INTO sys_dict_type (dict_code, dict_name, description, status, sort, deleted)
            VALUES (code, r.column_name, null, 1, 0, 0)
            RETURNING dict_type_id INTO dict_id;

            UPDATE sys_meta_table_column
            SET dict_code = code,
                options   = NULL
            WHERE id = r.column_id;

            FOR e IN SELECT jsonb_array_elements(r.options::jsonb)
                LOOP
                    INSERT INTO sys_dict_item (dict_type_id, item_code, item_label, sort, status, deleted)
                    VALUES (dict_id, e ->> 'value', e ->> 'label', 0, 1, 0);
                END LOOP;
        END LOOP;
END $$;

-- 新增系统管理菜单：字典配置
INSERT INTO sys_menu (menu_id, menu_name, menu_type, router_name, parent_id, path, is_button, permission, meta_info,
                      status, remark, creator_id, create_time, updater_id, update_time, deleted)
VALUES (88, '字典配置', 1, 'SystemDict', 1, '/system/dict/index', 0, 'system:dict:list',
        '{"title":"字典配置","icon":"ep:collection","showParent":true}', 1, '字典配置菜单', 1,
        '2025-08-06 00:00:00', 1, '2025-08-06 00:00:00', 0)
ON CONFLICT (menu_id) DO NOTHING;

INSERT INTO sys_menu (menu_id, menu_name, menu_type, router_name, parent_id, path, is_button, permission, meta_info,
                      status, remark, creator_id, create_time, updater_id, update_time, deleted)
VALUES (89, '字典查询', 0, ' ', 88, '', 1, 'system:dict:query', '{"title":"字典查询"}', 1, '', 1,
        '2025-08-06 00:00:00', 1, '2025-08-06 00:00:00', 0)
ON CONFLICT (menu_id) DO NOTHING;

INSERT INTO sys_menu (menu_id, menu_name, menu_type, router_name, parent_id, path, is_button, permission, meta_info,
                      status, remark, creator_id, create_time, updater_id, update_time, deleted)
VALUES (90, '字典新增', 0, ' ', 88, '', 1, 'system:dict:add', '{"title":"字典新增"}', 1, '', 1,
        '2025-08-06 00:00:00', 1, '2025-08-06 00:00:00', 0)
ON CONFLICT (menu_id) DO NOTHING;

INSERT INTO sys_menu (menu_id, menu_name, menu_type, router_name, parent_id, path, is_button, permission, meta_info,
                      status, remark, creator_id, create_time, updater_id, update_time, deleted)
VALUES (91, '字典修改', 0, ' ', 88, '', 1, 'system:dict:edit', '{"title":"字典修改"}', 1, '', 1,
        '2025-08-06 00:00:00', 1, '2025-08-06 00:00:00', 0)
ON CONFLICT (menu_id) DO NOTHING;

INSERT INTO sys_menu (menu_id, menu_name, menu_type, router_name, parent_id, path, is_button, permission, meta_info,
                      status, remark, creator_id, create_time, updater_id, update_time, deleted)
VALUES (92, '字典删除', 0, ' ', 88, '', 1, 'system:dict:remove', '{"title":"字典删除"}', 1, '', 1,
        '2025-08-06 00:00:00', 1, '2025-08-06 00:00:00', 0)
ON CONFLICT (menu_id) DO NOTHING;
