-- V10: 元表格 Schema 演进支持

-- 元表格增加 schema 版本号
ALTER TABLE sys_meta_table
    ADD COLUMN schema_version INT DEFAULT 1 NOT NULL;

-- 元表格字段增加后续阶段需要的关系与权限相关元数据（Schema 演进阶段仅做预留）
ALTER TABLE sys_meta_table_column
    ADD COLUMN reference_table  VARCHAR(64),
    ADD COLUMN reference_column VARCHAR(64),
    ADD COLUMN tenant_column    INT DEFAULT 0,
    ADD COLUMN owner_column     INT DEFAULT 0;

-- 元表格迁移记录表
CREATE TABLE IF NOT EXISTS sys_meta_table_migration
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_id        BIGINT       NOT NULL REFERENCES sys_meta_table (id),
    version         INT          NOT NULL,
    change_type     VARCHAR(32)  NOT NULL,
    column_code     VARCHAR(64),
    old_column_code VARCHAR(64),
    old_type        VARCHAR(64),
    new_type        VARCHAR(64),
    old_default     VARCHAR(255),
    new_default     VARCHAR(255),
    ddl_sql         TEXT         NOT NULL,
    status          VARCHAR(16)  NOT NULL DEFAULT 'PENDING',
    executed_at     TIMESTAMP,
    creator_id      BIGINT,
    create_time     TIMESTAMP,
    updater_id      BIGINT,
    update_time     TIMESTAMP,
    deleted         INT DEFAULT 0 NOT NULL,
    CONSTRAINT uq_meta_table_migration_version UNIQUE (table_id, version)
);

CREATE INDEX IF NOT EXISTS idx_meta_table_migration_table_id ON sys_meta_table_migration (table_id);
