-- V7: 文件管理模块
-- 创建 sys_file 表、文件存储默认参数、文件管理菜单与权限

-- 文件信息表
CREATE TABLE IF NOT EXISTS sys_file
(
    file_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    original_name VARCHAR(255)  DEFAULT '',
    storage_name  VARCHAR(255)  DEFAULT '',
    storage_path  VARCHAR(512)  DEFAULT '',
    file_size     BIGINT,
    content_type  VARCHAR(128)  DEFAULT '',
    extension     VARCHAR(32)   DEFAULT '',
    storage_type  VARCHAR(16)   DEFAULT 'local',
    remark        VARCHAR(512)  DEFAULT '',
    creator_id    BIGINT,
    create_time   TIMESTAMP,
    updater_id    BIGINT,
    update_time   TIMESTAMP,
    deleted       INT DEFAULT 0 NOT NULL
);

-- 为 sys_config 的 config_key 增加唯一约束
CREATE UNIQUE INDEX IF NOT EXISTS uq_sys_config_config_key ON sys_config (config_key);

-- 文件管理菜单
INSERT INTO sys_menu (menu_id, menu_name, menu_type, router_name, parent_id, path, is_button, permission, meta_info, status, remark, creator_id, create_time, deleted)
VALUES (66, '文件管理', 1, 'ToolFile', 3, '/tool/file/index', 0, 'tool:file:list', '{"title":"文件管理","icon":"ep:folder","showParent":true,"rank":2}', 1, '文件管理菜单', 1, NOW(), 0)
ON CONFLICT (menu_id) DO NOTHING;

-- 文件管理按钮权限
INSERT INTO sys_menu (menu_id, menu_name, menu_type, router_name, parent_id, path, is_button, permission, meta_info, status, remark, creator_id, create_time, deleted)
VALUES (67, '文件上传', 0, ' ', 66, '', 1, 'tool:file:upload', '{"title":"文件上传"}', 1, '', 1, NOW(), 0)
ON CONFLICT (menu_id) DO NOTHING;

INSERT INTO sys_menu (menu_id, menu_name, menu_type, router_name, parent_id, path, is_button, permission, meta_info, status, remark, creator_id, create_time, deleted)
VALUES (68, '文件删除', 0, ' ', 66, '', 1, 'tool:file:delete', '{"title":"文件删除"}', 1, '', 1, NOW(), 0)
ON CONFLICT (menu_id) DO NOTHING;

INSERT INTO sys_menu (menu_id, menu_name, menu_type, router_name, parent_id, path, is_button, permission, meta_info, status, remark, creator_id, create_time, deleted)
VALUES (69, '文件下载', 0, ' ', 66, '', 1, 'tool:file:download', '{"title":"文件下载"}', 1, '', 1, NOW(), 0)
ON CONFLICT (menu_id) DO NOTHING;

-- 把文件管理菜单权限赋给普通角色
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (2, 66) ON CONFLICT DO NOTHING;

INSERT INTO sys_role_menu (role_id, menu_id) VALUES (2, 67) ON CONFLICT DO NOTHING;

INSERT INTO sys_role_menu (role_id, menu_id) VALUES (2, 68) ON CONFLICT DO NOTHING;

INSERT INTO sys_role_menu (role_id, menu_id) VALUES (2, 69) ON CONFLICT DO NOTHING;

-- 重置序列
SELECT setval('sys_file_file_id_seq', COALESCE((SELECT MAX(file_id) FROM sys_file), 1));

SELECT setval('sys_menu_menu_id_seq', COALESCE((SELECT MAX(menu_id) FROM sys_menu), 1));

SELECT setval('sys_config_config_id_seq', COALESCE((SELECT MAX(config_id) FROM sys_config), 1));
