package com.lesofn.archforge.meta.table.internal.ddl;

import com.lesofn.archforge.meta.table.api.domain.MetaColumn;
import com.lesofn.archforge.meta.table.api.domain.MetaColumnType;
import com.lesofn.archforge.meta.table.api.domain.MetaTable;
import com.lesofn.archforge.meta.table.internal.exception.MetaTableErrorCode;
import com.lesofn.archforge.meta.table.internal.exception.MetaTableException;
import java.util.ArrayList;
import java.util.List;
import org.springframework.stereotype.Component;

/**
 * 元表格 DDL 生成器。
 */
@Component
public class MetaTableDdlGenerator {

    private static final int DEFAULT_VARCHAR_LENGTH = 255;
    private static final int DEFAULT_FILE_LENGTH = 512;
    private static final int DEFAULT_DECIMAL_PRECISION = 18;
    private static final int DEFAULT_DECIMAL_SCALE = 2;

    /** 生成物理表名。 */
    public String physicalTableName(MetaTable table) {
        String prefix = table.getTablePrefix() == null ? "meta_" : table.getTablePrefix();
        return prefix + table.getTableCode();
    }

    /** 生成创建物理表的 SQL 与索引 SQL。 */
    public DdlResult generateCreateTable(MetaTable table, List<MetaColumn> columns) {
        SqlIdentifier.validateTableCode(table.getTableCode());
        String physicalName = SqlIdentifier.quote(physicalTableName(table));

        StringBuilder createSql = new StringBuilder();
        createSql.append("CREATE TABLE IF NOT EXISTS ").append(physicalName).append(" (\n");
        createSql.append("    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n");
        createSql.append("    creator_id BIGINT,\n");
        createSql.append("    create_time TIMESTAMP,\n");
        createSql.append("    updater_id BIGINT,\n");
        createSql.append("    update_time TIMESTAMP,\n");
        createSql.append("    deleted INT DEFAULT 0 NOT NULL");

        List<String> indexStatements = new ArrayList<>();
        for (MetaColumn column : columns) {
            SqlIdentifier.validateColumnCode(column.getColumnCode());
            String columnDef = buildColumnDefinition(column);
            createSql.append(",\n    ").append(columnDef);

            if (column.isUniqueColumn()) {
                indexStatements.add(buildCreateIndex(table, column, true));
            } else if (column.isIndexedColumn()) {
                indexStatements.add(buildCreateIndex(table, column, false));
            }
        }

        createSql.append("\n)");
        return new DdlResult(createSql.toString(), indexStatements);
    }

    /** 生成删除物理表 SQL。 */
    public String generateDropTable(String physicalTableName) {
        return "DROP TABLE IF EXISTS " + SqlIdentifier.quote(physicalTableName) + " CASCADE";
    }

    private String buildColumnDefinition(MetaColumn column) {
        String name = SqlIdentifier.quote(column.getColumnCode());
        String type = resolveColumnType(column);
        StringBuilder sb = new StringBuilder();
        sb.append(name).append(' ').append(type);
        if (Boolean.TRUE.equals(column.getRequired())) {
            sb.append(" NOT NULL");
        }
        if (column.getDefaultValue() != null && !column.getDefaultValue().isEmpty()) {
            sb.append(" DEFAULT ").append(formatDefaultValue(column));
        }
        return sb.toString();
    }

    private String resolveColumnType(MetaColumn column) {
        MetaColumnType type = column.getDataType();
        if (type == null) {
            throw new MetaTableException(MetaTableErrorCode.META_COLUMN_TYPE_INVALID);
        }
        return switch (type) {
            case STRING, ENUM -> {
                int length = (column.getLength() == null || column.getLength() <= 0)
                        ? DEFAULT_VARCHAR_LENGTH
                        : column.getLength();
                yield "VARCHAR(" + length + ")";
            }
            case TEXT -> "TEXT";
            case INTEGER -> "BIGINT";
            case DECIMAL -> {
                int precision = (column.getPrecision() == null || column.getPrecision() <= 0)
                        ? DEFAULT_DECIMAL_PRECISION
                        : column.getPrecision();
                int scale = column.getScale() == null ? DEFAULT_DECIMAL_SCALE : column.getScale();
                yield "NUMERIC(" + precision + "," + scale + ")";
            }
            case BOOLEAN -> "BOOLEAN";
            case DATE -> "DATE";
            case DATETIME -> "TIMESTAMP";
            case JSON -> "JSONB";
            case FILE -> "VARCHAR(" + DEFAULT_FILE_LENGTH + ")";
        };
    }

    private String formatDefaultValue(MetaColumn column) {
        String value = column.getDefaultValue();
        return switch (column.getDataType()) {
            case STRING, TEXT, FILE, ENUM -> "'" + value.replace("'", "''") + "'";
            case INTEGER, DECIMAL -> value;
            case BOOLEAN -> Boolean.parseBoolean(value) ? "TRUE" : "FALSE";
            case DATE, DATETIME -> "'" + value + "'";
            case JSON -> "'" + value.replace("'", "''") + "'::jsonb";
        };
    }

    private String buildCreateIndex(MetaTable table, MetaColumn column, boolean unique) {
        String physicalName = physicalTableName(table);
        String indexName = (unique ? "uq_" : "idx_") + physicalName + "_" + column.getColumnCode();
        String prefix = indexName.length() > 63 ? indexName.substring(0, 63) : indexName;
        return "CREATE " + (unique ? "UNIQUE " : "") + "INDEX IF NOT EXISTS " + SqlIdentifier.quote(prefix) + " ON " +
                SqlIdentifier.quote(physicalName) + " (" + SqlIdentifier.quote(column.getColumnCode()) + ")";
    }

    /** DDL 生成结果：建表语句 + 索引语句列表。 */
    public record DdlResult(String createTableSql, List<String> indexSqls) {
    }
}
