-- V9: 元表格（meta table）模块
-- 创建元表格元数据表、物理表前缀/索引支持、菜单与权限

-- 元表格定义表
CREATE TABLE IF NOT EXISTS sys_meta_table
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_code    VARCHAR(64)  NOT NULL,
    table_name    VARCHAR(128) NOT NULL,
    description   VARCHAR(512) DEFAULT '',
    table_prefix  VARCHAR(32)  DEFAULT 'meta_',
    status        INT          DEFAULT 1 NOT NULL,
    creator_id    BIGINT,
    create_time   TIMESTAMP,
    updater_id    BIGINT,
    update_time   TIMESTAMP,
    deleted       INT DEFAULT 0 NOT NULL,
    CONSTRAINT uq_meta_table_code UNIQUE (table_code)
);

-- 元表格字段定义表
CREATE TABLE IF NOT EXISTS sys_meta_table_column
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_id        BIGINT       NOT NULL REFERENCES sys_meta_table (id),
    column_code     VARCHAR(64)  NOT NULL,
    column_name     VARCHAR(128) NOT NULL,
    data_type       VARCHAR(32)  NOT NULL,
    length          INT          DEFAULT 0,
    precision       INT          DEFAULT 0,
    scale           INT          DEFAULT 0,
    nullable        INT          DEFAULT 1,
    default_value   VARCHAR(255),
    is_unique       INT          DEFAULT 0,
    is_required     INT          DEFAULT 0,
    is_searchable   INT          DEFAULT 1,
    is_list_visible INT          DEFAULT 1,
    is_index        INT          DEFAULT 0,
    sort            INT          DEFAULT 0,
    options         TEXT,
    creator_id      BIGINT,
    create_time     TIMESTAMP,
    updater_id      BIGINT,
    update_time     TIMESTAMP,
    deleted         INT DEFAULT 0 NOT NULL,
    CONSTRAINT uq_meta_table_column UNIQUE (table_id, column_code)
);

CREATE INDEX IF NOT EXISTS idx_meta_table_column_table_id ON sys_meta_table_column (table_id);

-- 元表格菜单（顶级菜单）
INSERT INTO sys_menu (menu_id, menu_name, menu_type, router_name, parent_id, path, is_button, permission, meta_info, status, remark, creator_id, create_time, updater_id, update_time, deleted)
OVERRIDING SYSTEM VALUE
VALUES (80, '元表格', 1, 'MetaTable', 0, '/meta-table/index', 0, 'meta:table:list', '{"title":"元表格","icon":"ri:table-3","showParent":true,"rank":5}', 1, '元表格菜单', 1, '2022-05-21 08:30:54', 1, '2022-05-21 08:30:54', 0);

-- 元表格按钮权限
INSERT INTO sys_menu (menu_id, menu_name, menu_type, router_name, parent_id, path, is_button, permission, meta_info, status, remark, creator_id, create_time, updater_id, update_time, deleted)
OVERRIDING SYSTEM VALUE
VALUES (81, '元表格查询', 0, ' ', 80, '', 1, 'meta:table:query', '{"title":"元表格查询"}', 1, '', 1, '2022-05-21 08:30:54', 1, '2022-05-21 08:30:54', 0);

INSERT INTO sys_menu (menu_id, menu_name, menu_type, router_name, parent_id, path, is_button, permission, meta_info, status, remark, creator_id, create_time, updater_id, update_time, deleted)
OVERRIDING SYSTEM VALUE
VALUES (82, '元表格新增', 0, ' ', 80, '', 1, 'meta:table:add', '{"title":"元表格新增"}', 1, '', 1, '2022-05-21 08:30:54', 1, '2022-05-21 08:30:54', 0);

INSERT INTO sys_menu (menu_id, menu_name, menu_type, router_name, parent_id, path, is_button, permission, meta_info, status, remark, creator_id, create_time, updater_id, update_time, deleted)
OVERRIDING SYSTEM VALUE
VALUES (83, '元表格修改', 0, ' ', 80, '', 1, 'meta:table:edit', '{"title":"元表格修改"}', 1, '', 1, '2022-05-21 08:30:54', 1, '2022-05-21 08:30:54', 0);

INSERT INTO sys_menu (menu_id, menu_name, menu_type, router_name, parent_id, path, is_button, permission, meta_info, status, remark, creator_id, create_time, updater_id, update_time, deleted)
OVERRIDING SYSTEM VALUE
VALUES (84, '元表格删除', 0, ' ', 80, '', 1, 'meta:table:remove', '{"title":"元表格删除"}', 1, '', 1, '2022-05-21 08:30:54', 1, '2022-05-21 08:30:54', 0);

INSERT INTO sys_menu (menu_id, menu_name, menu_type, router_name, parent_id, path, is_button, permission, meta_info, status, remark, creator_id, create_time, updater_id, update_time, deleted)
OVERRIDING SYSTEM VALUE
VALUES (85, '元表格导出', 0, ' ', 80, '', 1, 'meta:table:export', '{"title":"元表格导出"}', 1, '', 1, '2022-05-21 08:30:54', 1, '2022-05-21 08:30:54', 0);

INSERT INTO sys_menu (menu_id, menu_name, menu_type, router_name, parent_id, path, is_button, permission, meta_info, status, remark, creator_id, create_time, updater_id, update_time, deleted)
OVERRIDING SYSTEM VALUE
VALUES (86, '元表格设计', 0, ' ', 80, '', 1, 'meta:table:design', '{"title":"元表格设计"}', 1, '', 1, '2022-05-21 08:30:54', 1, '2022-05-21 08:30:54', 0);

INSERT INTO sys_menu (menu_id, menu_name, menu_type, router_name, parent_id, path, is_button, permission, meta_info, status, remark, creator_id, create_time, updater_id, update_time, deleted)
OVERRIDING SYSTEM VALUE
VALUES (87, '元表格数据', 0, ' ', 80, '', 1, 'meta:table:data', '{"title":"元表格数据"}', 1, '', 1, '2022-05-21 08:30:54', 1, '2022-05-21 08:30:54', 0);

-- 把元表格菜单权限赋给管理员角色
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 80) ON CONFLICT DO NOTHING;
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 81) ON CONFLICT DO NOTHING;
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 82) ON CONFLICT DO NOTHING;
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 83) ON CONFLICT DO NOTHING;
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 84) ON CONFLICT DO NOTHING;
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 85) ON CONFLICT DO NOTHING;
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 86) ON CONFLICT DO NOTHING;
INSERT INTO sys_role_menu (role_id, menu_id) VALUES (1, 87) ON CONFLICT DO NOTHING;

-- 重置序列
SELECT setval('sys_meta_table_id_seq', COALESCE((SELECT MAX(id) FROM sys_meta_table), 1));
SELECT setval('sys_meta_table_column_id_seq', COALESCE((SELECT MAX(id) FROM sys_meta_table_column), 1));
SELECT setval('sys_menu_menu_id_seq', (SELECT COALESCE(MAX(menu_id), 0) FROM sys_menu));
